version: '3'
services:
  ui:
    build: './ui'
    environment:
    - REACT_APP_API_ENDPOINT=http://api:3000
    - PORT=8080
    links:
    - api:api
    ports:
    - "8080:80"
  api:
    build: './api'
    ports:
    - "3000:3000"
    environment:
    - BOGGLE_ROWS=4
    - BOGGLE_COLUMNS=4
    - ENVIRONMENT=dev
    - OXFORD_APP_ID=3736d866
    - OXFORD_APP_KEY=57a8b26396af5db64fe21fbffc31863a